[pytest]
# 命令行执行参数
addopts = -vs --strict-markers
# 排除目录
norecursedirs = Testcase/sub_dir_case
# 默认执行目录
testpaths = Testcase

# 执行规则：class
python_classes = Test*
# 执行规则：py文件
python_files = test_* *_test
# 执行规则：function
python_functions = test_*

## pycharm中，配置ids正常展示中文值
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

# xfail_strict默认false，标记为@pytest.mark.xfail的测试用例，如果是通过，显示XPASS
# 设置xfail_strict = true，标记为@pytest.mark.xfail且实际是通过（显示XPASS）的测试用例会被报告为失败FAILED
xfail_strict = false

# 日志开关 true/false、1/0
log_cli = 1
# 输出到terminal
# addopts = --capture=no # 打印详细日志，相当于命令行加 -vs
# 日志级别
log_cli_level = info
# 打印详细日志，相当于命令行加 -vs
# 日志格式
log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
# 日志时间格式
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    api:接口相关
    web:UI相关
    ut:单元测试
    login:登陆相关
    pay:支付相关
    mydata: 自定义标记1，用于传递数据到 fixture
    mydata2: 自定义标记2，用于传递数据到 fixture
    another: 自定义标记3，用于传递数据到 fixture
    multiplier: 自定义标记，用于获取测试函数上的标记